cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls import url, include

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

shopping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import include, url

admin.site.site_header = 'Django shopping'

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)

shop/models.py
from django.db import models
from django.urls import reverse
import datetime
import os
from django.utils.html import format_html
from django.utils.translation import ugettext as _
from ckeditor_uploader.fields import RichTextUploadingField

STATIC_UPLOAD_PRODUCT_URL = 'static/upload/product/'

class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

def upload_product_image(instance, filename):

    ext = filename.split('.')[-1]
    name = (instance.name).replace(" ", "_")
    filename = "%s_%s.%s" % (instance.slug, instance.id, ext)
    today = datetime.datetime.now()
    today_path = today.strftime("%Y/%m/%d")
    fullname = os.path.join(STATIC_UPLOAD_PRODUCT_URL + today_path + '/', filename)
    return fullname

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True, unique=True)
    description = RichTextUploadingField(null=True)
    # price = models.DecimalField(max_digits=10, decimal_places=2)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to=upload_product_image , blank=True)

    class Meta:
        ordering = ('-name', )
        index_together = (('id', 'slug'),)
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    def __str__(self):
        return self.name

    def image_tag(self):
        return format_html('<img src="%s" height="70px"/>' % (self.image.url))
    image_tag.short_description = ''
    image_tag.allow_tags = True

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

def product_image_slider(instance, filename):
    time = datetime.datetime.now().timestamp()
    folder_name = str(instance.product.id)
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (time, ext)
    fullname = os.path.join(STATIC_UPLOAD_PRODUCT_URL + folder_name + '/', filename)
    return fullname

class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='product_images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=product_image_slider, null=True)

    class Meta:
        verbose_name = _('Product Image')
        verbose_name_plural = _('Products Image')

    def image_tag(self):
        return format_html('<img src="%s" width="200px"/>' % (self.image.url))
    image_tag.short_description = ''
    image_tag.allow_tags = True

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

ITEM_PER_PAGE = 6

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True).order_by('-created_at')
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category).order_by('-created_at')

    paginator = Paginator(products, ITEM_PER_PAGE)
    page = request.GET.get('page')
    products_list = paginator.get_page(page)

    context = {
        'category': category,
        'categories': categories,
        'products': products_list,
    }
    return render(request, 'shop/product/list.html', context)


def product_detail(request, slug, id):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)

shop/templates/shop/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load i18n %}
{% load custom_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}On-line Shop{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
</head>
<body>
{% include 'shop/navbar.html' %}
<div class="container">
    <div class="row" style="margin-top: 6%">
        <!--<span class="badge pull-right" style="padding: 6px 12px; background: green">
            {% with totail_items=cart|length %}
                {% if cart|length > 0 %}
                    {% trans 'My Shopping Order:' %}
                    <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                        {{ totail_items }} {% trans 'item' %} {{ totail_items|pluralize }}, {{ cart.get_total_price|price_view }}
                    </a>
                    {% else %}
                    {% trans 'Your cart is empty.' %}
                {% endif %}
            {% endwith %}
        </span>-->

        <div class="btn-group pull-right cart_cus">
            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% with totail_items=cart|length %}
                    <i class="glyphicon glyphicon-shopping-cart"></i>
                    {% if cart|length > 0 %}
                        {{ totail_items }} {% trans 'item' %} {{ totail_items|pluralize }}, {{ cart.get_total_price|price_view }}
                    {% else %}
                        {% trans 'Your cart is empty.' %}
                    {% endif %}
                {% endwith %}
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu cart">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        <li class="cart-header">
                            {% with totail_items=cart|length %}
                                {% if cart|length > 0 %}
                                    <i class="glyphicon glyphicon-shopping-cart"></i><span class="badge bg-success">{{ totail_items }}</span>
                                    <div class="pull-right color_bbb">{% trans 'Total Cost:' %} <span class="color_green">{{ cart.get_total_price|price_view }}</span></div>
                                {% else %}
                                    {% trans 'Your cart is empty.' %}
                                {% endif %}
                            {% endwith %}
                        </li>
                        <li role="separator" class="divider"></li>
                        <li>
                            {% for item in cart %}
                                {% with product=item.product  %}
                                    <div class="row item vertical-align">
                                        <div class="col-xs-3 pr0">
                                            <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." >
                                        </div>
                                        <div class="col-xs-9">
                                            <div class="title">{{product.name}}</div>
                                            <div class="price">{{ item.total_price|price_view }} <span>{% trans 'Quantity' %}: {{ item.quantity }}</span></div>
                                        </div>
                                    </div>
                                {% endwith %}
                            {% endfor %}
                        </li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url "cart:cart_detail" %}" class="btn btn-checkout">Checkout</a></li>
                    {% else %}
                        <li><a href="#" class="btn btn-checkout">{% trans 'Your cart is empty.' %}</a></li>
                    {% endif %}
                {% endwith %}
            </ul>
        </div>
    </div>
</div>
{% block content %}


{% endblock %}


<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

shop/templates/shop/navbar.html
{% load static %}
{% load i18n %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0px; background-color: green;">
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'shop:product_list' %}" style="color: #ffffff">Django Shop</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <form action="{% url 'set_language' %}" method="post" id="set_language_form">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        {% for lang in LANGUAGES %}
                            {% if lang.0 == SELECTEDLANG %}
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">{{lang.1}} <span class="caret"></span></a>
                            {% endif %}
                        {% endfor %}
                        <ul class="dropdown-menu">
                            {% csrf_token %}
                            <input name="next" type="hidden" value="" />
                            {% for lang in LANGUAGES %}
                                {% if lang.0 != SELECTEDLANG %}
                                    <li><a class="submit_language_form" href="#" value="{{lang.0}}">{{ lang.1 }}</a></li>
                                {% endif %}
                            {% endfor %}
                            <input name="language" id="language" type="hidden" value=""/>
                        </ul>
                    </li>

                    <li class="dropdown">
                        {% if request.user.is_authenticated %}
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">{{ request.user.username }}<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="">{% trans 'Logout' %}</a></li>
                            </ul>
                        {% else %}
                            <li><a href="#" style="color: #ffffff">{% trans 'Sign in' %}</a></li>
                            <li><a href="#" style="color: #ffffff">{% trans 'Sign up' %}</a></li>
                        {% endif %}
                    </li>
                </ul>
            </form>

        </div><!-- /.navbar-collapse -->
    </div>
</nav>

<script>
    $(document).ready(function() { 
        $('.submit_language_form').click(function(e) {
            e.preventDefault();
            $('#set_language_form #language').val( $(this).attr("value"));
            $('#set_language_form').submit();
        });
    });
</script>